---
# handlers file for rke2-agent
- name: restart_agent
  service:
    name: rke2-agent
    state: restarted
    enabled: true
- name: restart_sysctl
  service:
    name: systemd-sysctl
    state: restarted